<?php
$cities = [
    "Kathmandu",
    "Lalitpur",
    "Bhaktapur",
    "Pokhara",
    "Bharatpur",
    "Biratnagar",
    "Birgunj",
    "Janakpur",
    "Dharan",
    "Hetauda",
    "Butwal",
    "Nepalgunj",
    "Dhangadhi",
    "Mahendranagar",
    "Itahari",
    "Tansen",
    "Ghorahi",
    "Jitpur Simara",
    "Gulariya",
    "Dashrathchand",
    "Besisahar",
    "Ilam",
    "Banepa",
    "Dhulikhel",
    "Panauti",
    "Kirtipur",
    "Madhyapur Thimi",
    "Suryabinayak",
    "Mahanarayan",
    "Anamnagar",
];
